### ISSUE TITLE
Issues peer-review

### ISSUE THREAD

**Issue by Agetuni** [ErikStoupignan/Capstone-m2-APIs-baseapp-pokemon#20]
![75b6c78c60c714b08f402c6b142e15cc](https://user-images.githubusercontent.com/45159038/187937616-2919eec6-b4fc-4b8d-872b-0ee6aa91993c.gif)

Good Job!

**Comment by Agetuni** [comment]
Please fix the merge issue

**Comment by dgsierra** [comment]
Done!
